id: IDB282A46
legacy_id: null
ocr_import_info:
  bdrc_scan_id: W3CN4660
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0002
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2023-12-16T17:15:01.304998'
last_modified: '2023-02-01T00:00:00+00:00'
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4660
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4660
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསྐྱེད་རྫོགས་ཟུང་འཇུག་གི་མན་ངག་ལམ་འབྲས་བུ་དང་བཅས་པའི་ཆོས་སྐོར།
  languages:
  - bo
  author: གཏེར་སྟོན་སངས་རྒྱས་གླིང་པ།
statistics: null
quality: null
bases:
  I3CN4662:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4662
      total_pages: 548
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I3CN4662.txt
    order: 1
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
  info_url: null
license: CC0
